/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main.java;

/**
 *
 * @author Gonzalo
 */
public class DetailsScreen extends javax.swing.JDialog {

    /**
     * Creates new form DetailsScreen
     */
    public DetailsScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuButtons = new javax.swing.JPanel();
        jButtonGoToPends = new javax.swing.JButton();
        jButtonGoToFavs = new javax.swing.JButton();
        jButtonGoToGeneral = new javax.swing.JButton();
        jButtonGoToDetails = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelAnimeTitle = new javax.swing.JLabel();
        jLabelAnimeImage = new javax.swing.JLabel();
        jLabelFavoriteChecked = new javax.swing.JLabel();
        jLabelPendingChecked = new javax.swing.JLabel();
        jLabelGenre1 = new javax.swing.JLabel();
        jLabelGenre2 = new javax.swing.JLabel();
        jLabelGenre3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSummary = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGoToPends.setText("Ver pendientes");
        jPanelMenuButtons.add(jButtonGoToPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 152, 41));

        jButtonGoToFavs.setText("Ver mis favoritos");
        jPanelMenuButtons.add(jButtonGoToFavs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 152, 41));

        jButtonGoToGeneral.setText("Ver todos");
        jPanelMenuButtons.add(jButtonGoToGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 152, 41));

        jButtonGoToDetails.setText("Ver detalles");
        jPanelMenuButtons.add(jButtonGoToDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 152, 41));

        getContentPane().add(jPanelMenuButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAnimeTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAnimeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelAnimeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 20, 380, 40));
        jPanel1.add(jLabelAnimeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 450));
        jPanel1.add(jLabelFavoriteChecked, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, 70));
        jPanel1.add(jLabelPendingChecked, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, 70));
        jPanel1.add(jLabelGenre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 60));
        jPanel1.add(jLabelGenre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 60));
        jPanel1.add(jLabelGenre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 100, 60));

        jTextAreaSummary.setColumns(20);
        jTextAreaSummary.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSummary);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 460, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 910, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailsScreen dialog = new DetailsScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGoToDetails;
    private javax.swing.JButton jButtonGoToFavs;
    private javax.swing.JButton jButtonGoToGeneral;
    private javax.swing.JButton jButtonGoToPends;
    private javax.swing.JLabel jLabelAnimeImage;
    private javax.swing.JLabel jLabelAnimeTitle;
    private javax.swing.JLabel jLabelFavoriteChecked;
    private javax.swing.JLabel jLabelGenre1;
    private javax.swing.JLabel jLabelGenre2;
    private javax.swing.JLabel jLabelGenre3;
    private javax.swing.JLabel jLabelPendingChecked;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenuButtons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSummary;
    // End of variables declaration//GEN-END:variables
}
