/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java;

/**
 *
 * @author gonza
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public MainScreen() {
        initComponents();
        jButtonGoToDetails.setVisible(false);
        jButtonGoToFavs.setVisible(false);
        jButtonGoToPends.setVisible(false);
        jButtonGoToGeneral.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuButtons = new javax.swing.JPanel();
        jButtonGoToPends = new javax.swing.JButton();
        jButtonGoToFavs = new javax.swing.JButton();
        jButtonGoToGeneral = new javax.swing.JButton();
        jButtonGoToDetails = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jLabelAppTitle = new javax.swing.JLabel();
        jLabelAppImage = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUserText = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPasswordText = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenuButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGoToPends.setText("Ver pendientes");
        jPanelMenuButtons.add(jButtonGoToPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 152, 41));

        jButtonGoToFavs.setText("Ver mis favoritos");
        jPanelMenuButtons.add(jButtonGoToFavs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 152, 41));

        jButtonGoToGeneral.setText("Ver todos");
        jPanelMenuButtons.add(jButtonGoToGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 152, 41));

        jButtonGoToDetails.setText("Ver detalles");
        jPanelMenuButtons.add(jButtonGoToDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 152, 41));

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAppTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAppTitle.setText("ANIMEGMER");
        jPanelMain.add(jLabelAppTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 16, 450, 30));
        jPanelMain.add(jLabelAppImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 710, 380));

        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("Iniciar sesión:");
        jPanelMain.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 80, 20));

        jLabelUser.setText("Usuario:");
        jPanelMain.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 60, 20));
        jPanelMain.add(jTextFieldUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 210, -1));

        jLabelPassword.setText("Usuario:");
        jPanelMain.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 60, 20));
        jPanelMain.add(jTextFieldPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 210, -1));

        jButtonEnter.setText("ENTRAR");
        jPanelMain.add(jButtonEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 140, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelMenuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addComponent(jPanelMenuButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonGoToDetails;
    private javax.swing.JButton jButtonGoToFavs;
    private javax.swing.JButton jButtonGoToGeneral;
    private javax.swing.JButton jButtonGoToPends;
    private javax.swing.JLabel jLabelAppImage;
    private javax.swing.JLabel jLabelAppTitle;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMenuButtons;
    private javax.swing.JTextField jTextFieldPasswordText;
    private javax.swing.JTextField jTextFieldUserText;
    // End of variables declaration//GEN-END:variables
}
