/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java;

/**
 *
 * @author Gonzalo
 */
public class PendingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PendingJPanel
     */
    public PendingJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPendings = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonDeleteFromPends = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPendings.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPendings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPendings.setText("MIS ANIMES PENDIENTES");
        add(jLabelPendings, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 17, 395, 33));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 68, 751, 392));

        jButtonDeleteFromPends.setText("Eliminar de pendientes");
        add(jButtonDeleteFromPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 503, 160, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteFromPends;
    private javax.swing.JLabel jLabelPendings;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
