/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main.java;

/**
 *
 * @author Gonzalo
 */
public class UserScreen extends javax.swing.JDialog {

    /**
     * Creates new form UserScreen
     */
    public UserScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUserTitle = new javax.swing.JLabel();
        jLabelUserImage = new javax.swing.JLabel();
        jLabelUserText = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelNumFavsText = new javax.swing.JLabel();
        jLabelNumFavs = new javax.swing.JLabel();
        jLabelNumPendsText = new javax.swing.JLabel();
        jLabelNumPends = new javax.swing.JLabel();
        jButtonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserTitle.setText("Datos de usuario");
        jPanel1.add(jLabelUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 19, 400, 50));
        jPanel1.add(jLabelUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 260, 230));
        jPanel1.add(jLabelUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, 30));

        jLabelUser.setText("Usuario:");
        jPanel1.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 60, 30));
        jPanel1.add(jLabelNumFavsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 200, 30));

        jLabelNumFavs.setText("Nº de Favoritos:");
        jPanel1.add(jLabelNumFavs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, 30));
        jPanel1.add(jLabelNumPendsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 200, 30));

        jLabelNumPends.setText("Nº de Pendientes:");
        jPanel1.add(jLabelNumPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, 30));

        jButtonLogOut.setText("Cerrar sesión");
        jPanel1.add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserScreen dialog = new UserScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabelNumFavs;
    private javax.swing.JLabel jLabelNumFavsText;
    private javax.swing.JLabel jLabelNumPends;
    private javax.swing.JLabel jLabelNumPendsText;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUserImage;
    private javax.swing.JLabel jLabelUserText;
    private javax.swing.JLabel jLabelUserTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
