/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package animeGMer;

/**
 *
 * @author Gonzalo
 */
public class DetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailsJPanel
     */
    public DetailsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAnimeTitle = new javax.swing.JLabel();
        jLabelAnimeImage = new javax.swing.JLabel();
        jLabelFavoriteChecked = new javax.swing.JLabel();
        jLabelPendingChecked = new javax.swing.JLabel();
        jLabelGenre1 = new javax.swing.JLabel();
        jLabelGenre2 = new javax.swing.JLabel();
        jLabelGenre3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSummary = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAnimeTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAnimeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelAnimeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 20, 380, 40));
        add(jLabelAnimeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 450));
        add(jLabelFavoriteChecked, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, 70));
        add(jLabelPendingChecked, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, 70));
        add(jLabelGenre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 60));
        add(jLabelGenre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 60));
        add(jLabelGenre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 100, 60));

        jTextAreaSummary.setColumns(20);
        jTextAreaSummary.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSummary);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 460, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnimeImage;
    private javax.swing.JLabel jLabelAnimeTitle;
    private javax.swing.JLabel jLabelFavoriteChecked;
    private javax.swing.JLabel jLabelGenre1;
    private javax.swing.JLabel jLabelGenre2;
    private javax.swing.JLabel jLabelGenre3;
    private javax.swing.JLabel jLabelPendingChecked;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSummary;
    // End of variables declaration//GEN-END:variables
}
