/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package animeGMer;

/**
 *
 * @author Gonzalo
 */
public class FavoriteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FavoriteJPanel
     */
    public FavoriteJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFavorites = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonDeleteFromFav = new javax.swing.JButton();
        jButtonComment = new javax.swing.JButton();
        jButtonRating = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFavorites.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFavorites.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFavorites.setText("MIS FAVORITOS");
        add(jLabelFavorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 16, 379, 32));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 66, 748, 392));

        jButtonDeleteFromFav.setText("Eliminar de mis favoritos");
        add(jButtonDeleteFromFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 484, -1, 33));

        jButtonComment.setText("Modificar comentario");
        add(jButtonComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 484, 159, 33));

        jButtonRating.setText("Modificar puntuación");
        add(jButtonRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 484, -1, 33));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComment;
    private javax.swing.JButton jButtonDeleteFromFav;
    private javax.swing.JButton jButtonRating;
    private javax.swing.JLabel jLabelFavorites;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
