/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package animeGMer;

/**
 *
 * @author Gonzalo
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscador = new javax.swing.JTextField();
        jLabelBuscador = new javax.swing.JLabel();
        jButtonFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonAddToFav = new javax.swing.JButton();
        jButtonDeleteFav = new javax.swing.JButton();
        jButtonAddToPends = new javax.swing.JButton();
        jButtonDeletePend = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextFieldBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 386, 20));

        jLabelBuscador.setText("Buscador:");
        add(jLabelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 99, 20));

        jButtonFilter.setText("Filtrar");
        add(jButtonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 800, 470));

        jButtonAddToFav.setText("Añadir a Favoritos");
        add(jButtonAddToFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jButtonDeleteFav.setText("Borrar de favorirtos");
        add(jButtonDeleteFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, -1, -1));

        jButtonAddToPends.setText("Añadir a pendientes");
        add(jButtonAddToPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        jButtonDeletePend.setText("Eliminar de pendientes");
        add(jButtonDeletePend, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddToFav;
    private javax.swing.JButton jButtonAddToPends;
    private javax.swing.JButton jButtonDeleteFav;
    private javax.swing.JButton jButtonDeletePend;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JLabel jLabelBuscador;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBuscador;
    // End of variables declaration//GEN-END:variables
}
