/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animeGMer;

/**
 *
 * @author gonza
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuButtons = new javax.swing.JPanel();
        jButtonGoToPends = new javax.swing.JButton();
        jButtonGoToFavs = new javax.swing.JButton();
        jButtonGoToGeneral = new javax.swing.JButton();
        jButtonGoToDetails1 = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jTextFieldBuscador = new javax.swing.JTextField();
        jLabelBuscador = new javax.swing.JLabel();
        jButtonFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonAddToFav = new javax.swing.JButton();
        jButtonDeleteFav = new javax.swing.JButton();
        jButtonAddToPends = new javax.swing.JButton();
        jButtonDeletePend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenuButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGoToPends.setText("Ver pendientes");
        jPanelMenuButtons.add(jButtonGoToPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 211, 152, 41));

        jButtonGoToFavs.setText("Ver mis favoritos");
        jPanelMenuButtons.add(jButtonGoToFavs, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 152, 41));

        jButtonGoToGeneral.setText("Ver todos");
        jPanelMenuButtons.add(jButtonGoToGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 34, 152, 41));

        jButtonGoToDetails1.setText("Ver detalles");
        jPanelMenuButtons.add(jButtonGoToDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 93, 152, 41));

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMain.add(jTextFieldBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 29, 386, -1));

        jLabelBuscador.setText("Buscador:");
        jPanelMain.add(jLabelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, 99, -1));

        jButtonFilter.setText("Filtrar");
        jPanelMain.add(jButtonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 29, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanelMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 1116, 454));

        jButtonAddToFav.setText("Añadir a Favoritos");
        jPanelMain.add(jButtonAddToFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 607, -1, -1));

        jButtonDeleteFav.setText("Borrar de favorirtos");
        jPanelMain.add(jButtonDeleteFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 607, -1, -1));

        jButtonAddToPends.setText("Añadir a pendientes");
        jPanelMain.add(jButtonAddToPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 607, -1, -1));

        jButtonDeletePend.setText("Eliminar de pendientes");
        jPanelMain.add(jButtonDeletePend, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 607, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelMenuButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenuButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddToFav;
    private javax.swing.JButton jButtonAddToPends;
    private javax.swing.JButton jButtonDeleteFav;
    private javax.swing.JButton jButtonDeletePend;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonGoToDetails1;
    private javax.swing.JButton jButtonGoToFavs;
    private javax.swing.JButton jButtonGoToGeneral;
    private javax.swing.JButton jButtonGoToPends;
    private javax.swing.JLabel jLabelBuscador;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMenuButtons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBuscador;
    // End of variables declaration//GEN-END:variables
}
