/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package animeGMer;

/**
 *
 * @author Gonzalo
 */
public class UserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserJPanel
     */
    public UserJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserTitle = new javax.swing.JLabel();
        jLabelUserImage = new javax.swing.JLabel();
        jLabelUserText = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelNumFavsText = new javax.swing.JLabel();
        jLabelNumFavs = new javax.swing.JLabel();
        jLabelNumPendsText = new javax.swing.JLabel();
        jLabelNumPends = new javax.swing.JLabel();
        jButtonLogOut = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserTitle.setText("Datos de usuario");
        add(jLabelUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 19, 400, 50));
        add(jLabelUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 260, 230));
        add(jLabelUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 110, 30));

        jLabelUser.setText("Usuario:");
        add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 60, 30));
        add(jLabelNumFavsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 110, 30));

        jLabelNumFavs.setText("Nº de Favoritos:");
        add(jLabelNumFavs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, 30));
        add(jLabelNumPendsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 110, 30));

        jLabelNumPends.setText("Nº de Pendientes:");
        add(jLabelNumPends, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, 30));

        jButtonLogOut.setText("Cerrar sesión");
        add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 140, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabelNumFavs;
    private javax.swing.JLabel jLabelNumFavsText;
    private javax.swing.JLabel jLabelNumPends;
    private javax.swing.JLabel jLabelNumPendsText;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUserImage;
    private javax.swing.JLabel jLabelUserText;
    private javax.swing.JLabel jLabelUserTitle;
    // End of variables declaration//GEN-END:variables
}
